const provinsi = [
  { id: 11, name: 'ACEH', created_at: new Date(), updated_at: new Date() },
  {
    id: 12,
    name: 'SUMATERA UTARA',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 13,
    name: 'SUMATERA BARAT',
    created_at: new Date(),
    updated_at: new Date(),
  },
  { id: 14, name: 'RIAU', created_at: new Date(), updated_at: new Date() },
  { id: 15, name: 'JAMBI', created_at: new Date(), updated_at: new Date() },
  {
    id: 16,
    name: 'SUMATERA SELATAN',
    created_at: new Date(),
    updated_at: new Date(),
  },
  { id: 17, name: 'BENGKULU', created_at: new Date(), updated_at: new Date() },
  { id: 18, name: 'LAMPUNG', created_at: new Date(), updated_at: new Date() },
  {
    id: 19,
    name: 'KEPULAUAN BANGKA BELITUNG',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 21,
    name: 'KEPULAUAN RIAU',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 31,
    name: 'DKI JAKARTA',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 32,
    name: 'JAWA BARAT',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 33,
    name: 'JAWA TENGAH',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 34,
    name: 'DI YOGYAKARTA',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 35,
    name: 'JAWA TIMUR',
    created_at: new Date(),
    updated_at: new Date(),
  },
  { id: 36, name: 'BANTEN', created_at: new Date(), updated_at: new Date() },
  { id: 51, name: 'BALI', created_at: new Date(), updated_at: new Date() },
  {
    id: 52,
    name: 'NUSA TENGGARA BARAT',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 53,
    name: 'NUSA TENGGARA TIMUR',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 61,
    name: 'KALIMANTAN BARAT',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 62,
    name: 'KALIMANTAN TENGAH',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 63,
    name: 'KALIMANTAN SELATAN',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 64,
    name: 'KALIMANTAN TIMUR',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 65,
    name: 'KALIMANTAN UTARA',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 71,
    name: 'SULAWESI UTARA',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 72,
    name: 'SULAWESI TENGAH',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 73,
    name: 'SULAWESI SELATAN',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 74,
    name: 'SULAWESI TENGGARA',
    created_at: new Date(),
    updated_at: new Date(),
  },
  { id: 75, name: 'GORONTALO', created_at: new Date(), updated_at: new Date() },
  {
    id: 76,
    name: 'SULAWESI BARAT',
    created_at: new Date(),
    updated_at: new Date(),
  },
  { id: 81, name: 'MALUKU', created_at: new Date(), updated_at: new Date() },
  {
    id: 82,
    name: 'MALUKU UTARA',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 91,
    name: 'PAPUA BARAT',
    created_at: new Date(),
    updated_at: new Date(),
  },
  { id: 94, name: 'PAPUA', created_at: new Date(), updated_at: new Date() },
]

module.exports = provinsi
